/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_M1.h"
#include "MClock.h"
#include "M1_FWD_aliases.h"
#include "M1_FWD.h"
#include "UART.h"
#include "M1_BWD_aliases.h"
#include "M1_BWD.h"
#include "PWM_M2.h"
#include "M2_FWD_aliases.h"
#include "M2_FWD.h"
#include "M2_BWD_aliases.h"
#include "M2_BWD.h"
#include "Standby_aliases.h"
#include "Standby.h"
#include "PWM_Out_1_aliases.h"
#include "PWM_Out_1.h"
#include "PWM_Out_2_aliases.h"
#include "PWM_Out_2.h"
#include "M1QuadDec.h"
#include "M1QuadDec_PVT.h"
#include "M1_Phase1_aliases.h"
#include "M1_Phase1.h"
#include "M1_Phase2_aliases.h"
#include "M1_Phase2.h"
#include "M1Clock.h"
#include "M2QuadDec.h"
#include "M2QuadDec_PVT.h"
#include "M2_Phase1_aliases.h"
#include "M2_Phase1.h"
#include "M2_Phase2_aliases.h"
#include "M2_Phase2.h"
#include "isr_1ms.h"
#include "Timer_1.h"
#include "UART_IntClock.h"
#include "M1QuadDec_isr.h"
#include "M1QuadDec_Cnt16.h"
#include "M2QuadDec_isr.h"
#include "M2QuadDec_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

